### ISSUE TITLE
Using eschecs-console

### ISSUE THREAD

**Issue by fredvs** [rchastain/eschecs-console#1]
Hello Roland.

I did a (forbidden) fast test of eschecs-console.
Nice and it seems that they play faster than me!
Very impressive.

Some note about compilation:
In the build.sh I have to change the main pascal file into _eschecs-cl.pas_

Also on Unix, when you copy a executable, it loose his permission.

So all the engines are not set as executable anymore.
In that case you may change the permissions at loading of eschecs with

`{$IF DEFINED(unix)}
fpchmod(thefilenameofengine, S_IRWXU);
{$endif}`

This to make eschecs works out-of-the-box.

Now about the heavy part of eschecs-engine code.
What infos does need the engine to answer, all the positions of each piece or only the one moving?
What is the format of that infos and of the answer from the engine?

Thanks.

Fre;D

**Comment by fredvs** [comment]
Hello.

It seems that the rock is not accepted:

```
Black plays e8c8
Illegal move.
```

**Comment by rchastain** [comment]
Hello Fred!

Thank your for testing the program and starting this discussion.

> Some note about compilation:
> In the build.sh I have to change the main pascal file into _eschecs-cl.pas_
> 

It seems that you didn't use the latest version of the code. That issue has already been fixed.

> Also on Unix, when you copy a executable, it loose his permission.
> 
> So all the engines are not set as executable anymore.
> In that case you may change the permissions at loading of eschecs with
> 
> `{$IF DEFINED(unix)} fpchmod(thefilenameofengine, S_IRWXU); {$endif}`
> 
> This to make eschecs works out-of-the-box.
>

Thank you for the tip. Done in the latest commit.
 
> Now about the heavy part of eschecs-engine code.
> What infos does need the engine to answer, all the positions of each piece or only the one moving?
> What is the format of that infos and of the answer from the engine?
> 

It's a long story. Now Eschecs uses the UCI protocol. Take a look at _eschecs-c.debug_, you will understand how it works.

In the future I would like to support also the XBoard/WinBoard protocol.

> Thanks.
> 

Thanks to you!

**Comment by rchastain** [comment]
> Hello.
> 
> It seems that the rock is not accepted:
> 
> ```
> Black plays e8c8
> Illegal move.
> ```

Yes, I noticed that, but not yet had time to fix it. I think it's because Eschecs expects another notation.

As Eschecs supports the chess 960 variant, we have to deal with two different notations for castling. In chess 960 variant, the target square is the rook square.

The new Eschecs will support two other variants (Capablanca and Capablanca random). So be prepared to have headaches. :)

Regards.

Roland

**Comment by rchastain** [comment]
I made something for the castling issue. Please see latest commit.

But the black engine _really_ plays illegal moves. For example on this position he wants to play e8c8, which is illegal.

![image](https://user-images.githubusercontent.com/13957204/73604063-578f4800-458b-11ea-87ed-71e91c8aa35e.png)

Have a nice Sunday!

**Comment by fredvs** [comment]
Hello Roland

>  For example on this position he wants to play e8c8, which is illegal (because of the white queen threatening b8).

Ha I did not know that is was not allowed for a "roque", I was thinking that only the movement of the king may not be targeted by a enemy and here, from E8 to C8 it is not the case, the queen has as target B8, that is not in the movement of the king.

But maybe (surely) I miss something.

Fre;D

**Comment by fredvs** [comment]
Re-hello.

I did test last commit of eschecs-console.

Nice, you fixed the illegal roque.
And all works out-of-the-box.
And the game ended: black win!

Maybe you may add the name of the players engine, to know what is white and black.

Big congrats.

I will jump, asap, in the debug log.

Fre;D

**Comment by fredvs** [comment]
Re-re hello.

In my young age, e8c8 was not allowed in case like this:
![roque_illegal](https://user-images.githubusercontent.com/3421249/73623261-a648ea80-463c-11ea-9c7c-6b2ad811620f.png)

Here the bishop has D8 as target and it is in the walk of the king to go to C8.

But I know, everything is changing.

A bientôt.

Fre;D

**Comment by rchastain** [comment]
Hello Fred! Thank you for your messages. Yes, you are right, about the castling rule. I imagined my own rule. ;)

**Comment by rchastain** [comment]
OK, the castling thing is fixed. Six years after the start of the project! Without you maybe I would never have seen that bug, and would never have known the exact rule of castling!
Thank you very much Fred.

**Comment by rchastain** [comment]
> Two are better than one, because they have a good reward for their labor. For if they fall, the one will lift up his fellow; but woe to him who is alone when he falls, and doesn't have another to lift him up.

_Ecclesiastes_, 4, 10.

**Comment by fredvs** [comment]
Hello Roland.

Wow for your eschecs-c.log.

Does it exist a method in Eschecs to convert the FEN line (position of all pieces) into a array 8x8?
Or maybe I have to code to decode the FEN and translate into a more friendly grid format?

Maybe it would be interesting to have also a eschecs-c engine-free that only does check of move. And the player will have to enter his "best move" and not all the FEN position.

But maybe too I did not understand that it is what Eschecs does and that I have to study the code before asking stupid questions.

Salut Roland!

Fre;D
Fre;D

**Comment by rchastain** [comment]
Now the game is saved in a PGN file. The file can be opened in any software to view the game. I tested only with WinBoard.

**Comment by rchastain** [comment]
> Maybe it would be interesting to have also a eschecs-c engine-free that only does check of move. And the player will have to enter his "best move" and not all the FEN position.
> 
If I correctly understand what you want, there is a little program named _gamedemo.pas_, in the _tutorial_ folder, that does that. Of course it can be improved. Please take a look at it and tell me if it does what you wish.

**Comment by fredvs** [comment]
> there is a little program named gamedemo.pas

Ha, perfect.
Huh, ReadLn(LInput), what is the format of Limput, something like "c8d8" or all the FEN?

**Comment by rchastain** [comment]
> Wow for your eschecs-c.log.
> 
Thank you.

> Does it exist a method in Eschecs to convert the FEN line (position of all pieces) into a array 8x8?
> Or maybe I have to code to decode the FEN and translate into a more friendly grid format?
> 
To convert a FEN string, you have the function _EncodePositionData_ in _fen.pas_.

**Comment by fredvs** [comment]
> To convert a FEN string, you have the function EncodePositionData in fen.pas.

Ok, I think I have all.

Thanks.

Fre;D

**Comment by rchastain** [comment]
> > there is a little program named gamedemo.pas
> 
> Ha, perfect.
> Huh, ReadLn(LInput), what is the format of LInput, something like "c8d8" or all the FEN?

It's "c8d8".

**Comment by rchastain** [comment]
Good night Fred!

**Comment by fredvs** [comment]
OK, all ready, it will be much easier that I was thinking to link it to msegui.

You have done a marvelous work Roland.

Good night Roland!

**Comment by fredvs** [comment]
```
Checkmate! Black wins.
Heap dump by heaptrc unit of /home/fred/eschecs-console-master/eschecs-c
544348 memory blocks allocated : 38593660/40899536
544348 memory blocks freed     : 38593660/40899536
0 unfreed memory blocks : 0
True heap size : 229376
True free heap : 229312
Should be : 229376

```

Aie, something wrong with memory leak, but ok, let forget it...
Re-good night!

**Comment by fredvs** [comment]
It must be from very last commits because with eschecs-c of +- 3 days ago:

```
Checkmate! Black wins.
Heap dump by heaptrc unit of /home/fred/Downloads/eschecs-console-master/eschecs-c
501023 memory blocks allocated : 34749581/36883792
501023 memory blocks freed     : 34749581/36883792
0 unfreed memory blocks : 0
True heap size : 163840
True free heap : 163840

```

So, sleep well, it will be easy to fix.
And I will go to sleep too now.

**Comment by fredvs** [comment]
Hello.

I am sleeping but in my dream it says that in commit "Reorganize directory"  commit fa8d49.
there is something wrong with `CommandLine;`

Fre;D

**Comment by rchastain** [comment]
Hello Fred!

Thank you for your message. I made a quick search in Lazarus forum and here is what I found. The experts say that the only important thing is "0 unfreed blocks". Please see [this message](https://forum.lazarus.freepascal.org/index.php/topic,42340.msg295359.html#msg295359) and [this one](https://forum.lazarus.freepascal.org/index.php/topic,38387.msg260445.html#msg260445).

So you can sleep in peace. But it's good that you raised that question. Now we know what to think.

Regards.

Roland

**Comment by rchastain** [comment]
The _commandline_ unit isn't used for now.

**Comment by fredvs** [comment]
Hello Roland.

> Please see this message and this one.

Hum, mouais, if they say it, but, mouais.
I did try last Eschecs with -ghl option at compilation.

And strangely, now there is no more heaptrc message at all.
It is like heaptrc is no more called.
Very strange.
Any way if on your system no more memory leak, it is ok.

But strange that suddenly heaptrc is not working anymore.
...

Ha, OK, I get it, you did add:

 `{$IF DECLARED(USEHEAPTRACE)}                 
  GlobalSkipIfNoLeaks := TRUE;
{$IFEND}`

Indeed with this no more problems!

> The commandline unit isn't used for now.

Ha, ok, because it is not removed from uses section in last commits.
I did remove commandline from uses section of eschecs-c.pas and indeed it is not needed, all compile ok.

But the most strange is that removing commandline from uses section and also removing 
 GlobalSkipIfNoLeaks := TRUE; gives this:

```
Heap dump by heaptrc unit of /home/fred/Downloads/eschecs-console-master/eschecs-c
431021 memory blocks allocated : 29200071/31034392
431021 memory blocks freed     : 29200071/31034392
0 unfreed memory blocks : 0
True heap size : 196608
True free heap : 196608

```

So, perfect, if commandline is not absolutely needed, maybe remove it completely from use section.

Fre;D

**Comment by fredvs** [comment]
Hello Roland.

May I ask you what do commandline + FLRE + PUCU ?
What does it that fpc cannot do?

Thanks.

Fre;D

**Comment by fredvs** [comment]
Re-hello Roland.

Sorry to monopolize.
The memory leak problems comes from this in commandline.pas:

```
initialization
 LCmdLine := Concat(' ', CmdLine, ' ');
```
Something is not freed after this, if you remove it, you will see that there are no more memory leak problems.

Maybe in `finalization` something must be added but I did not investigate what is not freed with
` LCmdLine := Concat(' ', CmdLine, ' ');`

Fre.D

**Comment by rchastain** [comment]
Hello Fred!

I don't know what means the message "should be etc." from the heaptrc unit, but if there is no message when SkipIfNoLeaks is set to true, for me it means that there is no leak.

FLRE is a very good library for regular expressions. Regular expressions are used in several parts of the Eschecs project. The current code uses RegExpr, but with time I would like to replace it by FLRE (which is faster and Delphi compatible). If you want, because I like you, we can keep two implementations.

By the way, if you don't know [BeRo1985](https://github.com/BeRo1985), you should take a look at his work.

**Comment by rchastain** [comment]
> Re-hello Roland.
> 
> Sorry to monopolize.
> The memory leak problems comes from this in commandline.pas:
> 
> ```
> initialization
>  LCmdLine := Concat(' ', CmdLine, ' ');
> ```
> 
> Something is not freed after this, if you remove it, you will see that there are no more memory leak problems.
> 
> Maybe in `finalization` something must be added but I did not investigate what is not freed with
> ` LCmdLine := Concat(' ', CmdLine, ' ');`
> 
> Fre.D

Well done, Fred. Glad to know that the issue (if this is really an issue) doesn't come from the FLRE library.

Maybe I shouldn't use the initialization section like I do.

Maybe we should try:

```
finalization
  LCommand := '';
```

**Comment by fredvs** [comment]
Hello Roland.

No, I am always open to new project and FLRE seems very interesting.
And after deep check, the memory leak does not come from there.

I did try with gdb and it find also memory leak with 
i```
nitialization
 LCmdLine := Concat(' ', CmdLine, ' ');
```
I will investigate from what comes the problem, from Concat or from CmdLine.

Fre.D

Fre;D

**Comment by rchastain** [comment]
Thank you Fred.

**Comment by fredvs** [comment]
Problems come from `CmdLine`.

**Comment by fredvs** [comment]
Usually CmdLine is used from
`TProcess.CommandLine (deprecated)`

But here it seems to come from a other component: `https://wiki.freepascal.org/CmdLine`
You may try, insert in your code, for example at beginning of procedure Play(), add 
`LCmdLine := Concat(' ', CmdLine, ' ');`

It will generate a memory leak.

Fre;D

**Comment by fredvs** [comment]
Last shot for this afternoon:

In https://wiki.freepascal.org/CmdLine

```
Dependencies / System Requirements
    LCL >=1.0
Status: Beta 
```

CmdLine needs LCL but, afaik, eschecs-console does not use LCL.
Maybe there is something related with this.

Fre;D

**Comment by rchastain** [comment]
OK Fred. I will replace CmdLine: I don't really need it. Thank you for your investigations.

Have a good afternoon!

Regards.

Roland

**Comment by fredvs** [comment]
Hello Roland.

Sorry to borrow you with those things.

Strange about **CmdLine**, I did test this:
```

program cmdlinetest;

begin
cmdline
end.
```

Compiled with this:

`fpc -ghl cmdlinetest.pas`

Gives this as result:

```
Heap dump by heaptrc unit of "cmdlinetest"
0 memory blocks allocated : 0/0
0 memory blocks freed     : 0/0
0 unfreed memory blocks : 0
True heap size : 294912
True free heap : 294848
Should be : 294912

```

???

**Comment by fredvs** [comment]
Re...re hello Roland.

Yep, I did try your last commit using `ParamStr(i)` and now it is much more reassuring:

```
Checkmate! Black wins.
Heap dump by heaptrc unit of /home/fred/Downloads/eschecs-console-master/eschecs-c
412334 memory blocks allocated : 29764255/31483992
412334 memory blocks freed     : 29764255/31483992
0 unfreed memory blocks : 0
True heap size : 196608
True free heap : 196608
```
So good end of afternoon and I am happy to forget about CmdLine (that, imho, has a little chunk of memory not removed in procedure SetupCmdLine of system.pp).

Fre;D

**Comment by rchastain** [comment]
OK Fred. Thank you for the confirmation.

Good afternoon to you too.
